### ISSUE TITLE
Support Multiple Modifier keys (e.g. CTRL+Alt+Tab)

### ISSUE THREAD

**Issue by kinland** [James-LG/AutoCursorLock#10]
The current UI only allows a single modifier key, but many Windows shortcuts use two or more. I'd like to use CTRL+ALT+TAB or something like that as my shortcut, but I'm instead forced to pick CTRL+TAB, etc.

With only a single modifier, the odds of overlapping an existing shortcut go WAY up, and there are way fewer workable combinations!

**Comment by James-LG** [comment]
Thanks for the suggestion. It will be in the next release.

**Comment by James-LG** [comment]
Now available in [v2.0.0](https://github.com/James-LG/AutoCursorLock/releases/tag/v2.0.0).
