### ISSUE TITLE
Cannot see full path/names in the 'add processes' or 'enabled processes' section

### ISSUE THREAD

**Issue by kinland** [James-LG/AutoCursorLock#11]
Since most executables have >= 3 path segments, virtually everything under both Enabled Processes and Add Processes shows an ellipsis (...). Since there are no tooltips, it's impossible to distinguish between two programs that have similar names, or discern between two that have similar paths.

I propose either adding a tooltip that shows the full path, or a single-column mode toggle that doesn't crop the path/exe name.

**Comment by James-LG** [comment]
There already is a tooltip. Screenshot taken with v1.1.2.

![image](https://github.com/user-attachments/assets/67fa1c34-5532-4b86-8b2e-1b34c6b1ac8b)
