### ISSUE TITLE
Cannot generate settings file automatically

### ISSUE THREAD

**Issue by KujouYuko** [James-LG/AutoCursorLock#16]
## Version

- v2.0.0

## Bug

```
An unhandled exception occurred: Could not find file 'C:\Users\KujouYuko\AppData\Roaming\AutoCursorLock\settings.json'.
```

[error.log](https://github.com/user-attachments/files/16705674/error.log)

## Description

I'm using the latest version of AutoCursorLock and it doesn't automatically generate a new settings file when there is no old one.

## Screenshot

![QQ20240822-132423](https://github.com/user-attachments/assets/81a16b1d-47d8-4974-98a6-043b114ec6cf)

**Comment by James-LG** [comment]
Apologies. Fixed in [v2.0.1](https://github.com/James-LG/AutoCursorLock/releases/tag/v2.0.1).
