### ISSUE TITLE
mouse going to other screen while firefox focus (window)

### ISSUE THREAD

**Issue by luukatyuo** [James-LG/AutoCursorLock#24]
Hi there, 
mouse is catched by firefox as it should, but when i try to move it from the right screen (firefox) to the left screen it will hover over to the left screen "a little bit" before it is blocked.
It wouldnt bother me, but If than i leftclick, the mouse is going freely @ left screen (guess this part isnt buggy).

I added a picture, i made with ma phone (couldnt screenshot with mouse arrow) to make it more clear for u.

PS a workaround is using "monitor-lock". Here it does work as it should.

![mouse right](https://github.com/user-attachments/assets/ad01be5d-37f2-43fa-9c9b-aac83a56070e)

thank u!

**Comment by James-LG** [comment]
Sorry for late response. I don't know why the border is off for firefox, but I added support for manual margin adjustment for these edge cases in [v2.1.0](https://github.com/James-LG/AutoCursorLock/releases/tag/v2.1.0).

Settings looks like this 
![image](https://github.com/user-attachments/assets/d7aba661-4646-4b53-a876-fc4ac353192c)


Feel free to reopen if this does not solve the issue.

**Comment by luukatyuo** [comment]
thank u
