### ISSUE TITLE
Start Minimized without windows Notification

### ISSUE THREAD

**Issue by Neko14789** [James-LG/AutoCursorLock#27]
Is it possible to start this tool minimized without the Windows Notification ("Minimized to tray...") so you can add it to autostart without any extra notification messages?

**Comment by IsaacShoebottom** [comment]
Also requesting this, thank you!

**Comment by IsaacShoebottom** [comment]
Workaround I just found. If you add it to your startup through a shortcut to your `shell:startup` folder, and customize the shortcut to start minimized like this
![image](https://github.com/user-attachments/assets/01364a6e-8505-4cd7-ba15-147b0435891f)
It will instantly minimize to tray

**Comment by James-LG** [comment]
Thanks for the suggestion. Option added in v2.2.0 which starts on windows boot without any notification.

See #30 for details.
