### ISSUE TITLE
AutoCursorLock does not recognize .NET Framework 4.8.1

### ISSUE THREAD

**Issue by A-nonymous027** [James-LG/AutoCursorLock#5]
Title says everything.
![image](https://github.com/James-LG/AutoCursorLock/assets/79244637/a854f957-be1d-4e3e-b09d-cc8308b26be3)

**Comment by James-LG** [comment]
Version 1.1.1 was using a very out of date .NET 5.

I just released v1.1.2 which requires .NET 7 or higher.

https://github.com/James-LG/AutoCursorLock/releases/tag/v1.1.2
https://dotnet.microsoft.com/en-us/download/dotnet/8.0
