### ISSUE TITLE
Does not work with Elden Ring (windows 10 64bit) ?

### ISSUE THREAD

**Issue by Bogdanov89** [James-LG/AutoCursorLock#7]
I tried this program specifically for Elden Ring, since it notoriously allows the mouse cursor to leave the game window every time any kind of menu has been opened regardless of is it "full screen" or "windowed mode" (map, inventory, equipment etc..).

Unfortunately no matter what i tried the AutoCursorLock did not prevent the Elden Ring from allowing the cursor to wander onto my 2nd monitor.

On a side note its a bit unclear what is the meaning of the above red line "Cursor Locked: False" when the below green line states "Locking Enabled: True"... the messages are contradictory and confusing to a simple end user.
No matter what i tried the above message in red did not change from False.

Here is a screenshot of the config (i tried pressing the hotkey many times and exiting & starting up the program).
Thanks for trying to solve this really annoying issue Windows imposes on us all.

![image](https://github.com/James-LG/AutoCursorLock/assets/55892027/225debff-68ec-4a1a-bc41-ed511746b596)

**Comment by James-LG** [comment]
Yeah they definitely seem a bit confusing. The lower one is basically whether the program is attempting to detect windows to lock on to. The upper one is whether the cursor is locked at that exact moment. 

Would "Locking enabled" -> "Window detection enabled" be better? Or something else.

---

Does the upper "Cursor Locked" change to True when Elden Ring is in focus?

**Comment by Bogdanov89** [comment]
Hey thanks for replying & explaining!
Honestly i would not mind a more verbose description, be it as the main colored text or as some kind of an additional line of text below the main colored text explaining what the current state & intent is.

I tried ER+AutoCursorLock a few more times and it seems that the above text does change to the green True while ERing is in focus - but the actual mouse cursor itself is not locked in any way.
The mouse cursor in Elden Ring behaves the same with or without AutoCursorLock.
That is to say that as soon as any kind of map/inventory/equipment is open the mouse can leave the ERing window and the only way to lock it back into ERing is to (furiously) click 5+ times into the game window.

Thank you for working on this issue!

**Comment by James-LG** [comment]
Interesting. Can you download and run [DebugView ](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview)(made by Microsoft), and see if there are any errors being printed while using AutoCursorLock?

![image](https://github.com/James-LG/AutoCursorLock/assets/1709432/15d0f262-a08e-4d68-bf9b-ff30b1f5e346)

**Comment by Nzxtime** [comment]
Hi, I have also tried this and in my case the eldenring process doesn't show up in AutoCursorLock (with and without admin rights).

Before, I tried [this](https://www.snakebytestudios.com/projects/apps/cursor-lock/) program but it (also) lets the cursor wander off to other screens slightly.

**Comment by Aluerie** [comment]
> Interesting. Can you download and run [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview)

Also having same issue, the cursor just doesn't get locked within Elden Ring (seems working fine for other windows)

![image](https://github.com/user-attachments/assets/cfca5aed-e7fb-48a7-9ba2-207d1d651b10)

Here are the logs from debug view, but there is no error message in here :D 
![image](https://github.com/user-attachments/assets/1a7e050c-20cb-487b-b011-e27389269ab7)

**Comment by Nzxtime** [comment]
My current workaround is to use [Dual Monitor Tools](https://dualmonitortool.sourceforge.net/) and lock the cursor to a specific monitor and by holding Ctrl I can bypass the lock.

**Comment by James-LG** [comment]
@Aluerie thanks for testing it with DebugView.

The fact that there are no errors means either Elden Ring is not reporting its window size correctly, or it is actually clearing the window lock.

If it's the window size problem then I could add a setting to lock the cursor to a monitor rather than a window. The difference between that and Dual Monitor tools would be that it locks in when the window is in focus, and unlocks as soon as you alt-tab.

**Comment by James-LG** [comment]
The next release will support locking the cursor to the monitor the window is on. Hopefully that fixes the issue.

**Comment by Aluerie** [comment]
Unfortunately, again, it works perfectly with other apps/games but Elden Ring (and Sekiro - also Fromsoft's game) - nope.

The logs again don't have any error.
![image](https://github.com/user-attachments/assets/1bcb442c-26c1-40b2-9806-0f64196746ce)

**Comment by James-LG** [comment]
I do own Sekiro so I can test that out later.

**Comment by fritzw** [comment]
It also does not work with the game Grounded, which recently fails to lock my cursor. Neither in "Lock to Window" nor in "Lock to Monitor" mode. Its window name is "Maine-Win64-Shipping", for whatever reason.

Weirdly enough, it also doesn't work for any other program, like VS Code, or Putty. Maybe it's a problem with my machine, perhaps I should try rebooting...

Here's the log file: [log.txt](https://github.com/user-attachments/files/17970207/log.txt)

**Comment by fritzw** [comment]
Okay, the game locks the cursor like normal after a reboot, so no need for your tool. Maybe some other unknown program was causing all cursor locks to fail. Sorry for the useless comment above.

(However, it might be helpful for future users to know that a reboot could help)

**Comment by James-LG** [comment]
Extremely late reply, but since I got Elden Ring during this winter sale I decided to troubleshoot this a bit more, and unfortunately I can confirm Elden Ring is clearing the cursor lock for some reason.

I can add an option to periodically re-apply the cursor lock but it will never be perfect as AutoCursorLock fights to keep your cursor within bounds, meaning it would be possible to click something outside of bounds if you click at the perfectly wrong time.

**Comment by James-LG** [comment]
I added an option in v2.2.0 to re-apply the cursor lock on a configurable interval. It's not the best solution because your cursor can still leave the window, but when combined with a configurable margin (already implemented), I think this is the best it's gonna get so I'm closing the issue.

Details in #28.

Side-note, but I noticed while troubleshooting that the sound you get when hovering over menu buttons in Elden Ring still plays when there's a window on top of Elden Ring, so it's clearly doing something weird. Putting this here in case someone else knows more about what Elden Ring is doing in the future.

**Comment by halflumi** [comment]
In case anyone stumbled upon the same hurdle, with a hook on `ClipCursor` (user32.dll), this is pretty easy to solve, which is good enough for offline and Seamless Co-op. Example:

```
HWND CursorLockHook::FindGameWindow() {
	HWND hwnd = nullptr;
	DWORD pid = GetCurrentProcessId();

	// Find the main window belonging to this process
	do {
		hwnd = FindWindowExW(nullptr, hwnd, nullptr, nullptr);
		if (hwnd) {
			DWORD windowPid = 0;
			GetWindowThreadProcessId(hwnd, &windowPid);
			if (windowPid == pid && GetWindow(hwnd, GW_OWNER) == nullptr && IsWindowVisible(hwnd)) {
				return hwnd;
			}
		}
	} while (hwnd);

	return nullptr;
}

BOOL WINAPI CursorLockHook::ClipCursorHook(const RECT* lpRect) {
	if (lpRect == nullptr) {
		// The game is trying to release the cursor clip — block it and
		// re-clip to the game window instead.
		HWND hwnd = FindGameWindow();
		if (hwnd) {
			RECT clientRect;
			if (GetClientRect(hwnd, &clientRect)) {
				POINT topLeft = { clientRect.left, clientRect.top };
				POINT bottomRight = { clientRect.right, clientRect.bottom };
				ClientToScreen(hwnd, &topLeft);
				ClientToScreen(hwnd, &bottomRight);

				RECT screenRect;
				screenRect.left = topLeft.x;
				screenRect.top = topLeft.y;
				screenRect.right = bottomRight.x;
				screenRect.bottom = bottomRight.y;

				return ClipCursorOriginal(&screenRect);
			}
		}
		// If we can't find the window, just suppress the unclip
		return TRUE;
	}

	// Non-null rect: let it through normally
	return ClipCursorOriginal(lpRect);
}
```

**Comment by James-LG** [comment]
@halflumi Neat! If you want you can post a PR and I'll merge it to help others.
