### ISSUE TITLE
Register hot key without modifier keys

### ISSUE THREAD

**Issue by chaes666** [James-LG/AutoCursorLock#8]
工作中会遇到公共电脑，只允许用户使用数学键或字母键其它键不允许使用以及使用鼠标在规定范围点击的功能。

**Comment by James-LG** [comment]
I don't know what this means.

**Comment by chaes666** [comment]
At work, you may encounter public computers that only allow users to use math keys or letter keys. Other keys are not allowed to be used, and the mouse cannot be used to click within a specified range.

**Comment by James-LG** [comment]
Unfortunately the Win32 API only supports the following modifier keys: ALT, CTRL, SHIFT, WINDOWS. See docs here: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey

I'm not sure there's another way around it if you can't click those keys for some reason.

I'm surprised you can even download this program on a PC that doesn't let you press SHIFT. How do you even use a keyboard without SHIFT?

**Comment by chaes666** [comment]
It's like this scenario: I only want the mouse to be used inside the browser, and only the number keys of the keyboard can be used. Other keys such as F1-F12, ESC and other combinations are artificially disabled. Maybe I'm describing it wrong, but thank you. (This message was translated using a translation software, my English is not good.)

**Comment by James-LG** [comment]
#12 also added support for no-modifier hotkeys. Will be available in the next version.
