### ISSUE TITLE
Toggle Hotkey doesn't work

### ISSUE THREAD

**Issue by kinland** [James-LG/AutoCursorLock#9]
The lock-to-window functionality seems to work, and I can bind a toggle hotkey in the UI, but the hotkey doesn't appear to actually work. When I press the hotkey, nothing happens. The AutoCursorLock window continues to say "Locking enabled." I've tried both with AutoCursorLock window with focus, as well as with an enabled game in focus.

Strangely, if I bind something like "None + F" as my shortcut, then my F key stops working, but it still doesn't toggle the lock status. If I then change it to "None + G," now my F key and my G key don't work anymore (it doesn't release the F key).

I do not know if it is relevant, but I have Windows 11 23H2

**Comment by James-LG** [comment]
I found a bug in how the hot key was being registered. Unclear if it's your problem, but the fix is in [v2.0.0](https://github.com/James-LG/AutoCursorLock/releases/tag/v2.0.0).
